version: '2'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }

services:

  django:
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://debug:debug@postgres/pesados_el_norte
    image: pesados_el_norte_local_django
    container_name: django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    volumes:
      - .:/app:z
      - ./pesados_el_norte:/app/pesados_el_norte:z
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: pesados_el_norte_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: pesados_el_norte_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./pesados_el_norte:/app/pesados_el_norte:z
    ports:
      - "7000:7000"
    command: /start-docs


